#!/usr/bin/env bash

### changing fecal sample fastq headers to satisfy CutAdapt requirements
input_path_fecal="/cloud/project/deinterleaved_fecal_samples/"
output_path_fecal="/cloud/project/new_header_fecal_samples/"
for i in 2 4 6 7 8 9 10 12 13 15 16 17 19 20 21 23 24 26 27 28 29 30 31 35 36
do
  sed 's/\([A-Z0-9]*\.[0-9]*\)\s\s\([0-9]*\/[0-9]\)/\1\/\2/' "${input_path_fecal}SSPt${i}-1.fq" > "${output_path_fecal}fixedheader_SSPt${i}-1.fq"
  sed 's/\([A-Z0-9]*\.[0-9]*\)\s\s\([0-9]*\/[0-9]\)/\1\/2/' "${input_path_fecal}SSPt${i}-2.fq" > "${output_path_fecal}fixedheader_SSPt${i}-2.fq"
done

### changing jejunal sample fastq headers to satisfy CutAdapt requirements
input_path_jejunal="/cloud/project/deinterleaved_jejunal_samples/"
output_path_jejunal="/cloud/project/new_header_jejunal_samples/"
for i in 1 2 3 4 6 7 8 9 12 13 14 15 16 17 19 20 21 23 24 26 27 28 29 30 31 35 36 
do
  sed 's/\([A-Z0-9]*\.[0-9]*\)\s\s\([0-9]*\/[0-9]\)/\1\/\2/' "${input_path_jejunal}JAPt${i}-1.fq" > "${output_path_jejunal}fixedheader_JAPt${i}-1.fq"
  sed 's/\([A-Z0-9]*\.[0-9]*\)\s\s\([0-9]*\/[0-9]\)/\1\/2/' "${input_path_jejunal}JAPt${i}-2.fq" > "${output_path_jejunal}fixedheader_JAPt${i}-2.fq"
done
